/*
 * Generated by MTK DrvGen Version 5.03.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Mar 13 15:26:05 2013
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_HF_MIC_CHANNEL     1
#define AUXADC_UTMS_CHANNEL     2
#define AUXADC_TEMPERATURE_CHANNEL     3


#endif //_CUST_AUXADC_TOOL_H


