/*
 * Generated by MTK DrvGen Version 5.03.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Mar 13 15:26:05 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


